services:
  acme.bookstore.httpapi.host:
    container_name: bookstore-backend
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: src/Acme.BookStore.HttpApi.Host/Dockerfile
  angular:
    container_name: bookstore-frontend
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: ./angular
      dockerfile: Dockerfile.local
  db-migrator:
    image: acme/bookstore-db-migrator:latest
    container_name: db-migrator
    build:
      context: .
      dockerfile: src/Acme.BookStore.DbMigrator/Dockerfile.local
  mysql:
    image: mysql:8.0
    container_name: mysql
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_server
    build:
      context: .
      dockerfile: Dockerfile.jenkins
