FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y docker.io openssh-client curl gnupg && \
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN usermod -aG docker jenkins

RUN mkdir -p /var/jenkins_home/.ssh && \
ssh-keyscan github.com > /var/jenkins_home/.ssh/known_hosts

RUN chown -R jenkins:jenkins /var/jenkins_home

RUN apt-get install -y curl libicu-dev && \
    curl -sSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh && \
    chmod +x dotnet-install.sh && \
    ./dotnet-install.sh --version latest --channel 9.0 --install-dir /usr/share/dotnet && \
    ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet && \
    rm dotnet-install.sh && \
    apt-get remove -y curl && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER jenkins