AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  ProjectName:
    Type: String
  AppDomain:
    Type: String
  HostedZoneId:
    Type: String

Resources:
  CloudFrontCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref AppDomain
      SubjectAlternativeNames:
        - !Sub "*.${AppDomain}"
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref AppDomain
          HostedZoneId: !Ref HostedZoneId

Outputs:
  CloudFrontCertificateArn:
    Value: !Ref CloudFrontCertificate
    Export:
      Name: !Sub "${ProjectName}-CloudFrontCertArn"
