AWSTemplateFormatVersion: "2010-09-09"
Description: Secrets Manager for TLS certificates

Parameters:
  ProjectName:
    Type: String
  SignCertB64:
    Type: String
    NoEcho: true
  EncCertB64:
    Type: String
    NoEcho: true

Resources:
  SignCertSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: sign.pfx.b64
      Description: Signing certificate PFX base64
      SecretString: !Ref SignCertB64

  EncCertSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: enc.pfx.b64
      Description: Encryption certificate PFX base64
      SecretString: !Ref EncCertB64

Outputs:
  SignCertSecretArn:
    Value: !Ref SignCertSecret
    Export:
      Name: !Sub "${ProjectName}-SignCertSecretArn"
  EncCertSecretArn:
    Value: !Ref EncCertSecret
    Export:
      Name: !Sub "${ProjectName}-EncCertSecretArn"
