name: Build and Deploy to ECS Fargate

on:
  workflow_dispatch:
    inputs:
      git_branch:
        description: 'Branch to build'
        required: true
        default: 'aws'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-southeast-1
      PROJECT_NAME: bookstore-demo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get branch name (sanitize for Docker tag)
        id: branch
        shell: bash
        run: |
          RAW_BRANCH="${GITHUB_REF##*/}"
          SAFE_BRANCH=$(echo "$RAW_BRANCH" | tr '/' '-' | tr -cd '[:alnum:]._-')
          echo "BRANCH_NAME=$SAFE_BRANCH" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Dynamic Infrastructure Parameters (from CFN Exports)
        run: |
          TASK_DEF=$"{{ env.PROJECT_NAME }}-DotnetTaskDefArn"
          DB_ENDPOINT=$(aws cloudformation list-exports --query "Exports[?Name=='${{env.PROJECT_NAME}}-DBEndpointAddress'].Value" --output text --region ${{ env.AWS_REGION }})
          DB_PORT=$(aws cloudformation list-exports --query "Exports[?Name=='${{env.PROJECT_NAME}}-DBEndpointPort'].Value" --output text --region ${{ env.AWS_REGION }})
          TASK_ROLE_ARN=$(aws cloudformation list-exports --query "Exports[?Name=='${{env.PROJECT_NAME}}-ECSTaskToReadBookStoreSecretsRoleArn'].Value" --output text --region ${{ env.AWS_REGION }})
          TASK_EXECUTION_ROLE_ARN=$(aws cloudformation list-exports --query "Exports[?Name=='${{env.PROJECT_NAME}}-ECSTaskExecutionRoleArn'].Value" --output text --region ${{ env.AWS_REGION }})
          ECR_REPOSITORY_NAME=$(aws cloudformation list-exports --query "Exports[?Name=='${{env.PROJECT_NAME}}-MainECRRepositoryName'].Value" --output text --region ${{ env.AWS_REGION }})  
          ECR_URI="$AWS_ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ECR_REPOSITORY_NAME"
          ECS_SERVICE=$"{{ env.PROJECT_NAME }}-Dotnet-Service"
          ECS_CLUSTER=$"{{ env.PROJECT_NAME }}-ECSCluster"

          echo "TASK_DEF=$TASK_DEF" >> $GITHUB_ENV
          echo "DB_ENDPOINT=$DB_ENDPOINT" >> $GITHUB_ENV
          echo "DB_PORT=$DB_PORT" >> $GITHUB_ENV
          echo "DB_USER=admin" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.MYSQL_BOOKSTORE_DB_PASSWORD }}" >> $GITHUB_ENV
          echo "TASK_ROLE_ARN=$TASK_ROLE_ARN" >> $GITHUB_ENV
          echo "TASK_EXECUTION_ROLE_ARN=$TASK_EXECUTION_ROLE_ARN" >> $GITHUB_ENV
          echo "IMAGE_URI=$ECR_URI:dotnet-${{ env.BRANCH_NAME }}" >> $GITHUB_ENV
          echo "ECR_URI=$ECR_URI" >> $GITHUB_ENV
          echo "ECS_SERVICE=$ECS_SERVICE" >> $GITHUB_ENV
          echo "ECS_CLUSTER=$ECS_CLUSTER" >> $GITHUB_ENV

      - name: Render ECS task definition
        run: |
          cat ecs-task-def.json | \
            sed "s|\${TASK_DEF}|${TASK_DEF}|g" | 
            sed "s|\${DB_ENDPOINT}|${DB_ENDPOINT}|g" | \
            sed "s|\${DB_PORT}|${DB_PORT}|g" | \
            sed "s|\${DB_USER}|${DB_USER}|g" | \
            sed "s|\${DB_PASSWORD}|${DB_PASSWORD}|g" | \
            sed "s|\${IMAGE_URI}|${IMAGE_URI}|g" | \
            sed "s|\${TASK_ROLE_ARN}|${TASK_ROLE_ARN}|g" | \
            sed "s|\${TASK_EXECUTION_ROLE_ARN}|${TASK_EXECUTION_ROLE_ARN}|g" | \
            > ecs-task-def.rendered.json

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: docker build -f src/Acme.BookStore.HttpApi.Host/Dockerfile -t ${{ env.ECR_URI }}:dotnet-${{ env.BRANCH_NAME }} .

      - name: Push image to Amazon ECR
        run: docker push ${{ env.ECR_URI }}:dotnet-${{ env.BRANCH_NAME }}

      - name: Fill in new image in ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs-task-def.rendered.json
          container-name: dotnet
          image: ${{ env.ECR_URI }}:dotnet-${{ env.BRANCH_NAME }}

      - name: Deploy ECS Service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
