name: Infrastructure and Application Initialization

on:
  workflow_dispatch: # Giữ lại: Cho phép chạy thủ công (Phát triển)
    inputs:
      git_branch:
        description: 'Branch for migration'
        required: true
        default: 'aws'

env:
  AWS_REGION: ap-southeast-1
  PROJECT_NAME: bookstore-demo
  VPCCIDR: 10.0.0.0/16
  APP_DOMAIN: bookstore-demo.online
  HOSTED_ZONE_ID: Z00108562GUIWSZXR6B6E
  CLOUDFRONT_HOSTED_ZONE_ID: Z2FDTNDATAQYW2
  ALB_CERT_ARN: arn:aws:acm:ap-southeast-1:211125699268:certificate/5a8c4030-882d-44de-9b02-a28e1cc5ceca
  CLOUDFRONT_CERT_ARN: arn:aws:acm:us-east-1:211125699268:certificate/e393ede3-6f85-4876-9fdd-f20a03c3ebc2
  DB_USERNAME: admin
  APP_PORT: 8080
  MYSQL_PORT: 3306
  SIGN_CERT_SECRET_ARN: arn:aws:secretsmanager:ap-southeast-1:211125699268:secret:sign.pfx.b64-*
  ENCRYPT_CERT_SECRET_ARN: arn:aws:secretsmanager:ap-southeast-1:211125699268:secret:enc.pfx.b64-*
  CFN_MODULES_PATH: ./cloudformation/

jobs:
  # =======================================================
  # JOB 1: INFRA-SETUP (Tạo Network, Security, Database, Compute/ECR, ALB/CF)
  # =======================================================
  infra-setup:
    runs-on: ubuntu-latest
    outputs:
      ecr_repo_uri: ${{ steps.get-ecr-uri.outputs.ecr_repo_uri }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 1. Deploy NETWORK Stack
        run: |
          aws cloudformation deploy \
            --template-file ${{ env.CFN_MODULES_PATH }}/network-stack.yml \
            --stack-name ${{ env.PROJECT_NAME }}-Network-Stack \
            --parameter-overrides \
                ProjectName=${{ env.PROJECT_NAME }} \
                VPCCIDR=${{ env.VPCCIDR }} \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM 
            
          VPC_ID=$(aws cloudformation describe-stacks \
            --stack-name ${{ env.PROJECT_NAME }}-Network-Stack \
            --query "Stacks[0].Outputs[?ExportName=='${{ env.PROJECT_NAME }}-VPCId'].OutputValue" \
            --output text)
            
            echo "VPC_ID=$VPC_ID" >> $GITHUB_ENV # Lưu VPC_ID vào môi trường

      - name: 2. Deploy SECURITY Stack
        run: |
          aws cloudformation deploy \
            --template-file ${{ env.CFN_MODULES_PATH }}/security-stack.yml \
            --stack-name ${{ env.PROJECT_NAME }}-Security-Stack \
            --parameter-overrides \
                ProjectName=${{ env.PROJECT_NAME }} \
                VPCId=${{ env.VPC_ID }} \
                AppPort=${{ env.APP_PORT }} \
                MysqlPort=${{ env.MYSQL_PORT }} \
                SigningCertificateSecretArn=${{ env.SIGN_CERT_SECRET_ARN }} \
                EncryptionCertificateSecretArn=${{ env.ENCRYPT_CERT_SECRET_ARN }} \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM 
            
      - name: 3. Deploy DATABASE Stack
        run: |
          aws cloudformation deploy \
            --template-file ${{ env.CFN_MODULES_PATH }}/database-stack.yml \
            --stack-name ${{ env.PROJECT_NAME }}-Database-Stack \
            --parameter-overrides \
                ProjectName=${{ env.PROJECT_NAME }} \
                DBUsername=${{ env.DB_USERNAME }} \
                DBPassword=${{ secrets.MYSQL_BOOKSTORE_DB_PASSWORD }} \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM 

      - name: 4. Deploy COMPUTE Stack (Tạo ECR/Cluster/TaskDefs)
        id: get-ecr-uri
        run: |
          aws cloudformation deploy \
            --template-file ${{ env.CFN_MODULES_PATH }}/compute-stack.yml \
            --stack-name ${{ env.PROJECT_NAME }}-Compute-Stack \
            --parameter-overrides \
                ProjectName=${{ env.PROJECT_NAME }} \
                AppPort=${{ env.APP_PORT }} \
                DBUsername=${{ env.DB_USERNAME }} \
                DBPassword=${{ secrets.MYSQL_BOOKSTORE_DB_PASSWORD }} \
                BranchName=${{ github.ref_name }} \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM 
            
          ECR_REPO_NAME=$(aws cloudformation describe-stacks \
            --stack-name ${{ env.PROJECT_NAME }}-Compute-Stack \
            --query "Stacks[0].Outputs[?ExportName=='${{ env.PROJECT_NAME }}-MainECRRepositoryName'].OutputValue" \
            --output text)
            
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
          ECR_URI="$AWS_ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ECR_REPO_NAME"

          echo "ecr_repo_uri=$ECR_URI" >> $GITHUB_OUTPUT

      - name: 5. Deploy LOAD BALANCER / CLOUDFRONT Stack
        run: |
          aws cloudformation deploy \
            --template-file ${{ env.CFN_MODULES_PATH }}/alb-cf-stack.yml \
            --stack-name ${{ env.PROJECT_NAME }}-LoadBalancer-Stack \
            --parameter-overrides \
                ProjectName=${{ env.PROJECT_NAME }} \
                AppDomain=${{ env.APP_DOMAIN }} \
                AppPort=${{ env.APP_PORT }} \
                HostedZoneId=${{ env.HOSTED_ZONE_ID }} \
                CloudfrontHostedZoneId=${{ env.CLOUDFRONT_HOSTED_ZONE_ID }} \
                ALBCertificateArn=${{ env.ALB_CERT_ARN }} \
                CloudFrontCertificateArn=${{ env.CLOUDFRONT_CERT_ARN }} \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM 

  # =======================================================
  # JOB 2: BUILD & PUSH IMAGES & COMPILED ANGULAR
  # =======================================================
  build-push:
    needs: infra-setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Trigger Angular Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: deploy_frontend # Tên sự kiện đã định nghĩa
          client-payload: '{ "ref": "${{ github.ref }}", "sha": "${{ github.sha }}" }'

      - name: Trigger DB Migration Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: deploy_migration
          client-payload: '{ "ref": "${{ github.ref }}", "sha": "${{ github.sha }}" }'

      - name: Trigger Dotnet Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: deploy_dotnet
          client-payload: '{ "ref": "${{ github.ref }}", "sha": "${{ github.sha }}" }'
